spring:
  application:
    name: eureka-server-master
    
eureka:
  instance:
    appname: eureka-server-master
    hostname: localhost
    
  client:
    register-with-eureka: true
    fetch-registry: true
    
data:
  env: eureka-server-master
  user:
    username: eureka-server-master-dev
    password: 1291029102
    
